import os
import datetime
from typing import Dict, List

def generate_markdown_playbook(incident_data: Dict, recommendations: List[str]) -> str:
    """
    Generates a Markdown playbook file for the incident.

    Args:
        incident_data (dict): The incident data from Layer 5 input.
        recommendations (list): List of recommended next steps from action_recommender.

    Returns:
        str: The file path of the generated playbook.
    """
    # Create shared/playbooks directory if it doesn't exist
    playbooks_dir = os.path.join(os.path.dirname(__file__), 'shared', 'playbooks')
    os.makedirs(playbooks_dir, exist_ok=True)

    # Extract relevant data from incident_data
    event_id = incident_data.get("event_id", "unknown")
    base_score = incident_data.get("base_score", 0.0)
    severity = incident_data.get("severity", "UNKNOWN")
    intent = incident_data.get("intent", "Unknown Threat")
    attacker_ip = incident_data.get("attacker_ip", "Unknown")
    affected_entity = incident_data.get("affected_entity", "Unknown")

    # Severity badge mapping
    severity_badges = {
        "CRITICAL": "🔴 CRITICAL",
        "HIGH": "🟠 HIGH",
        "MEDIUM": "🟡 MEDIUM",
        "LOW": "🟢 LOW",
        "UNKNOWN": "⚪ UNKNOWN"
    }
    severity_badge = severity_badges.get(severity.upper(), "⚪ UNKNOWN")

    # Generate playbook ID and timestamp
    timestamp = datetime.datetime.now().isoformat()
    playbook_id = f"PLAY-{event_id}"

    # Define the file path
    file_name = f"{playbook_id}.md"
    file_path = os.path.join(playbooks_dir, file_name)

    # Generate the markdown content
    markdown_content = f"""# 🛡️ tuxSOC Incident Response Playbook

## Incident Header
- **Playbook ID:** {playbook_id}
- **Event ID:** {event_id}
- **Timestamp:** {timestamp}
- **Severity:** {severity_badge}
- **CVSS Score:** {base_score}/10.0

## 🎯 Threat Intent
**{intent}**

## 🖥️ Affected Assets
- **Attacker IP:** {attacker_ip}
- **Affected Entity:** {affected_entity}

## ⚡ Automated Actions Already Taken
*(This section will be populated by the orchestration layer with actions taken)*

## 📋 Recommended Analyst Steps
"""

    # Add recommendations with checkboxes
    for i, rec in enumerate(recommendations, 1):
        markdown_content += f"{i}. [ ] {rec}\n"

    markdown_content += f"""
## 📝 Notes & Timeline
*Add investigation notes, commands run, and findings here.*

---
*Generated by tuxSOC Layer 5: Response Service*
*Playbook ID: {playbook_id}*
"""

    # Write the playbook to a Markdown file
    with open(file_path, 'w') as f:
        f.write(markdown_content)

    print(f"📖 Playbook generated: {file_path}")
    return file_path